### ISSUE TITLE
relative path for csv_header_properties

### ISSUE THREAD

**Issue by darkzbaron** [pe-st/garmin-connect-export#18]
Hi there,

On windows, if you run the script from another working directory you get the following error:

'''
IOError: [Errno 2] No such file or directory: 'csv_header_default.properties
''' 

This works however if you run the script from the script directory but this might deserve improvement.

**Comment by pe-st** [comment]
Thanks for reporting this oversight!
The latest commit on the develop branch should fix this, can you please retest?

**Comment by KristianLN** [comment]
Hi there,
I get the same problem at the moment, and it appears to be related to the fact that an extra backslash is added to the actual path.
So, if the correct path is C:\Users\Myname, the path used is C:\\Users\\Myname.
Any suggestions for a solution?

**Comment by KristianLN** [comment]
Hi there,

I still get the same problem, even if I execute the script from the script directory.
